### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by niall-m** [niall-m/ShouldReads#4]
- [ ] Users can view (index and show) books
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by chungkikelly** [comment]
If time permits, let's style it more, but otherwise looks good to me. 

The more you seed, the more professional your site looks. So make sure to loop back and seed more, even after the FSP's are technically over.
